- name: "Rest conf switch cisco L2"
  hosts: all
  connection: local
  gather_facts: no
  vars: 
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: "Get info version"
      ios_command:
        commands: show version 
      register: output
    - name: print output
      debug:
        var: output.stdout_lines