- name: "Get infomation device Cisco"
  hosts: switch
  connection: local
  gather_facts: no
  tasks:
    - name: "Get info version"
      ios_command:
        commands: show version
      register: output
    - name: print output
      debug:
        var: output.stdout_lines