- name: "Rest conf switch cisco L2"
  hosts: all
  ansible_connection: local
  gather_facts: no
  tasks:
    - name: "Get info version"
      set_fact:
        provider:
          username: admin
          password: buncha11
      ios_command:
        commands: show version | incl version
      register: output
    - name: print output
      debug:
        var: output.stdout_lines
