- name: "Rest conf switch cisco L2"
  hosts: "*"
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Get info version"
      ios_command:
        commands: show version | incl version
      register: output
    - name: print output
      debug:
        var: output.stdout_lines
