- name: "Rest conf switch cisco L2"
  hosts: all
  connection: network_cli
  gather_facts: false
  tasks:
    - name: "Get info version"
      ios_command:
        commands: show version
      register: version_output
    - name: print output
      debug:
        var: output.stdout_lines
