- name: Running bash on system
  hosts: localhost
  tasks:
    - name: 'Run a bash using an executable in a system path'
      command: bash /home/ansible/cbs_backups.sh
      register: result
    - debug:
        msg: "{{ result }}"
