- name: Running bash on system
  hosts: localhost
  tasks:
    - name: 'Run a bash using an executable in a system path'
      ansible.builtin.script:
        cmd: ../backups/backups.sh
        executable: /usr/bin/bash
      register: result
    - debug:
        msg: "{{ result }}"