---
- name: Show version and other user level commands
  hosts: cisco_test
  gather_facts: no
  connection: local

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios

  tasks:
  - name: run multipe commands
    ios_command:
      commands:
        - show version
        - show ip int brief

    register: print_output

  - debug: var=print_output.stdout_lines
