- name: Running bash on system
  hosts: snipeit
  tasks:
    - name: Run auto update EIM
      command: python3 auto-update-EIM/update_daily.py
      register: result
    - debug:
        msg: "{{ result }}"
