- name: Install Repository
  hosts: vmware_hosts
  tasks:
    - name: 'Install Repository and Package'
      apt:
        name: zabbix-agent
        state: present
        force_apt_get: yes
    - name: Copy Zabbix agent configuration for Linux
      copy:
        src: config_zabbix_agent/centos/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
    - name: Start the Zabbix agent
      service:
        name: zabbix-agent
        enabled: yes
        state: started


HostName:172.16.15.201
HostKeyAlgorithms=+ssh-dss
hostvars.localhost.DTG
sshpass -p 'Skylight1qaz@WSX' sftp gearinc@172.16.15.240:/Backup_Network/Zabbix <<<$'put -r zabbix.sql'